pub mod app;
pub mod events;
pub mod footer;
pub mod header;
pub mod history;
pub mod input;
pub mod layout;
pub mod components;
pub mod mvi;
pub mod pty;
pub mod render;
pub mod selection;
pub mod settings;
pub mod runtime;
pub mod terminal;
pub mod terminal_guard;
pub mod theme;

pub use runtime::run;
